# test:2.2:
#   image: ruby:2.2
#   script:
#   - bundle install
#   - bundle exec rake spec

docker_image:
  image: ruby:2.2
  script:
  - apt-get update -y
  - apt-get install -y apt-transport-https ca-certificates gnupg2
  - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - echo "deb https://apt.dockerproject.org/repo debian-jessie main" | tee /etc/apt/sources.list.d/docker.list
  - apt-get update -y
  - apt-get install docker-engine -y
  - bundle install
