stages:
  - test
  - build

test:2.2:
  stage: test
  image: ruby:2.2
  services:
  - mysql:latest
  variables:
    RAILS_ENV: ci
    MYSQL_DATABASE: pets
    MYSQL_ROOT_PASSWORD: root
  script:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rake spec

test:2.3:
  stage: test
  image: ruby:2.3
  services:
  - mysql:latest
  variables:
    RAILS_ENV: ci
    MYSQL_DATABASE: pets
    MYSQL_ROOT_PASSWORD: root
  script:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rake spec

test:2.4:
  stage: test
  image: ruby:2.4
  services:
  - mysql:latest
  variables:
    RAILS_ENV: ci
    MYSQL_DATABASE: pets
    MYSQL_ROOT_PASSWORD: root
  script:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rake spec


test:latest:
  stage: test
  image: ruby:latest
  services:
  - mysql:latest
  variables:
    RAILS_ENV: ci
    MYSQL_DATABASE: pets
    MYSQL_ROOT_PASSWORD: root
  script:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rake spec

docker_image:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
  - apk --update add --virtual build_deps build-base ruby-dev libc-dev linux-headers openssl-dev mysql-dev libxml2-dev libxslt-dev
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build . -t registry.gitlab.com/rodrigodealer/pets:1.0.0
  - docker push registry.gitlab.com/rodrigodealer/pets
