stages:
  - test
  - build
  - deploy

test:2.3:
  only:
  - test
  stage: test
  image: ruby:2.3
  services:
  - mysql:latest
  variables:
    RAILS_ENV: ci
    MYSQL_DATABASE: pets
    MYSQL_ROOT_PASSWORD: root
  script:
  - bundle install
  - bundle exec rails db:create RAILS_ENV=ci
  - bundle exec rails db:migrate RAILS_ENV=ci
  - bundle exec rake spec

test:2.4_latest:
  only:
  - test
  stage: test
  image: ruby:latest
  services:
  - mysql:latest
  variables:
    RAILS_ENV: ci
    MYSQL_DATABASE: pets
    MYSQL_ROOT_PASSWORD: root
  script:
  - bundle install
  - bundle exec rails db:create RAILS_ENV=ci
  - bundle exec rails db:migrate RAILS_ENV=ci
  - bundle exec rake spec

docker_image:
  only:
  - test
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
  - apk --update add --virtual build_deps build-base ruby-dev libc-dev linux-headers mariadb-dev libxml2-dev libxslt-dev
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build . -t registry.gitlab.com/rodrigodealer/pets:1.0.0
  - docker push registry.gitlab.com/rodrigodealer/pets

deploy:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update
  - apt-get install software-properties-common -y
  - apt-add-repository ppa:ansible/ansible
  - apt-get update
  - apt-get install ansible
  - cd ansible && ansible-playbook playbook.yml -l webserver -i hosts/hosts
  only:
  - master
