test:2.2:
  image: ruby:2.2
  script:
  - bundle install
  - bundle exec rake spec

docker_image:
  image: docker:git
  services:
    - docker:dind
  script:
  - apk --update add --virtual build_deps build-base ruby-dev libc-dev linux-headers openssl-dev postgresql-dev libxml2-dev libxslt-dev
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build . -t registry.gitlab.com/rodrigodealer/pets:1.0.0
  - docker push registry.gitlab.com/rodrigodealer/pets
