# test:2.2:
#   image: ruby:2.2
#   script:
#   - bundle install
#   - bundle exec rake spec

docker_image:
  image: docker:git
  services:
    - docker:dind
  script:
  - apk --update add --virtual build_deps build-base ruby-dev libc-dev linux-headers openssl-dev postgresql-dev libxml2-dev libxslt-dev
  # - apt-add-repository ppa:brightbox/ruby-ng
  # - apt-get update
  # - apt-get install ruby2.3 ruby2.3-dev -y
  # - apt-get update -y
  # - apt-get install -y apt-transport-https ca-certificates gnupg2
  # - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  # - echo "deb https://apt.dockerproject.org/repo debian-jessie main" | tee /etc/apt/sources.list.d/docker.list
  # - apt-get update -y
  # - apt-get install docker-engine -y
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build . -t registry.gitlab.com/rodrigodealer/pets:1.0.0
  - docker push registry.gitlab.com/rodrigodealer/pets
