stages:
  - test
  - build

test:2.2:
  stage: test
  image: ruby:2.2
  script:
  - bundle install
  - bundle exec rake spec

test:2.3:
  stage: test
  image: ruby:2.3
  script:
  - bundle install
  - bundle exec rake spec

test:2.4:
  stage: test
  image: ruby:2.4
  script:
  - bundle install
  - bundle exec rake spec


test:latest:
  stage: test
  image: ruby:latest
  script:
  - bundle install
  - bundle exec rake spec

docker_image:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
  - apk --update add --virtual build_deps build-base ruby-dev libc-dev linux-headers openssl-dev postgresql-dev libxml2-dev libxslt-dev
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build . -t registry.gitlab.com/rodrigodealer/pets:1.0.0
  - docker push registry.gitlab.com/rodrigodealer/pets
