require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::ProductTagsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ProductTag. As you add validations to ProductTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: 'Bla'}
  }

  let(:invalid_attributes) {
    {name: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductTagsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all product_tags as @product_tags" do
      product_tag = ProductTag.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:product_tags)).to eq([product_tag])
    end
  end

  describe "GET #show" do
    it "assigns the requested product_tag as @product_tag" do
      product_tag = ProductTag.create! valid_attributes
      get :show, params: {id: product_tag.to_param}, session: valid_session
      expect(assigns(:product_tag)).to eq(product_tag)
    end
  end

  describe "GET #new" do
    it "assigns a new product_tag as @product_tag" do
      get :new, params: {}, session: valid_session
      expect(assigns(:product_tag)).to be_a_new(ProductTag)
    end
  end

  describe "GET #edit" do
    it "assigns the requested product_tag as @product_tag" do
      product_tag = ProductTag.create! valid_attributes
      get :edit, params: {id: product_tag.to_param}, session: valid_session
      expect(assigns(:product_tag)).to eq(product_tag)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ProductTag" do
        expect {
          post :create, params: {product_tag: valid_attributes}, session: valid_session
        }.to change(ProductTag, :count).by(1)
      end

      it "assigns a newly created product_tag as @product_tag" do
        post :create, params: {product_tag: valid_attributes}, session: valid_session
        expect(assigns(:product_tag)).to be_a(ProductTag)
        expect(assigns(:product_tag)).to be_persisted
      end

      it "redirects to the created product_tag" do
        post :create, params: {product_tag: valid_attributes}, session: valid_session
        expect(response).to be_redirect
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved product_tag as @product_tag" do
        post :create, params: {product_tag: invalid_attributes}, session: valid_session
        expect(assigns(:product_tag)).to be_a_new(ProductTag)
      end

      it "re-renders the 'new' template" do
        post :create, params: {product_tag: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { name: 'Blah'}
      }

      it "updates the requested product_tag" do
        product_tag = ProductTag.create! valid_attributes
        put :update, params: {id: product_tag.to_param, product_tag: new_attributes}
        product_tag.reload

        expect(flash[:notice]).to match(/successfully updated/)
      end

      it "assigns the requested product_tag as @product_tag" do
        product_tag = ProductTag.create! valid_attributes
        put :update, params: {id: product_tag.to_param, product_tag: valid_attributes}
        expect(assigns(:product_tag)).to eq(product_tag)
        
        expect(flash[:notice]).to match(/successfully updated/)
      end

      it "redirects to the product_tag" do
        product_tag = ProductTag.create! valid_attributes
        put :update, params: {id: product_tag.to_param, product_tag: valid_attributes}
        expect(response).to be_redirect
      end
    end

    context "with invalid params" do
      it "assigns the product_tag as @product_tag" do
        product_tag = ProductTag.create! valid_attributes
        put :update, params: {id: product_tag.to_param, product_tag: invalid_attributes}, session: valid_session
        expect(assigns(:product_tag)).to eq(product_tag)
      end

      it "re-renders the 'edit' template" do
        product_tag = ProductTag.create! valid_attributes
        put :update, params: {id: product_tag.to_param, product_tag: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested product_tag" do
      product_tag = ProductTag.create! valid_attributes
      expect {
        delete :destroy, params: {id: product_tag.to_param}, session: valid_session
      }.to change(ProductTag, :count).by(-1)
    end

    it "redirects to the product_tags list" do
      product_tag = ProductTag.create! valid_attributes
      delete :destroy, params: {id: product_tag.to_param}, session: valid_session
      expect(response).to redirect_to(admin_product_tags_url)
    end
  end

end
