---
- name: Create directory for uploads
  file:
    path: /var/uploads
    owner: pets
    group: users
    mode: 064
    state: directory

- name: Restart docker
  service:
    name: docker
    state: restarted
  become: yes

- name: Login to gitlab registry
  become: yes
  command: docker login registry.gitlab.com -u rodrigodealer -p JrN6MmaCfsUFoBLHsx6U

- name: Pull image
  become: yes
  command: docker pull registry.gitlab.com/rodrigodealer/pets:1.0.0

- name: Copy upstart script for pets
  become: yes
  template:
    src: ../files/pets_api.j2
    dest: /etc/init/pets.conf
    owner: pets
    group: users
    mode: 0644

- name: Database migration
  copy:
    src: ../files/db_migrate.sh
    dest: /tmp/db_migrate.sh
  become: yes

- service:
    name: pets
    state: restarted
  become: yes

- name: Execute migration
  command: sh /tmp/db_migrate.sh > /tmp/log.txt
  become: yes
