---
- name: Login to gitlab registry
  docker_login:
    registry: registry.gitlab.com
    username: rodrigodealer
    password: JrN6MmaCfsUFoBLHsx6U

- name: Pull image
  docker_image:
    state: present
    name: registry.gitlab.com/rodrigodealer/pets
    tag: 1.0.0
