---
- name: Login to gitlab registry
  become: yes
  command: docker login registry.gitlab.com -u rodrigodealer -p JrN6MmaCfsUFoBLHsx6U

- name: Pull image
  become: yes
  command: docker pull registry.gitlab.com/rodrigodealer/pets:1.0.0
