development: &default
  host: <%= ENV['GITLAB_CI'] ? 'http://elasticsearch:9200' : 'http://localhost:9200'  %>
  transport_options:
    request:
      timeout: !!integer 300
test:
  <<: *default
  host: 'http://elasticsearch:9200/'
ci:
  <<: *default
  host: 'http://elasticsearch:9200/'
production:
  host: https://pels3miz64:h1zhcsiqk7@pet-in-a-6338750571.eu-west-1.bonsaisearch.net
  transport_options:
    request:
      timeout: !!integer 300
