development: &default
  host: '<%= ENV['GITLAB_CI'] ? 'http://elasticsearch:9200/' : 'http://localhost:9200/'  %>'
  transport_options:
    request:
      timeout: !!integer 300
test:
  <<: *default
  host: 'http://elasticsearch:9200/'
ci:
  <<: *default
  host: 'http://elasticsearch:9200/'
production:
  host: <%= ENV['ES_HOST'] %>
  transport_options:
    request:
      timeout: !!integer 300
