development: &default
  host: 'http://localhost:9200/'
  transport_options:
    request:
      timeout: !!integer 300
test:
  <<: *default
ci:
  <<: *default
  host: 'http://elasticsearch:9200/'
production:
  host: <%= ENV['ES_HOST'] %>
  transport_options:
    request:
      timeout: !!integer 300
